language: python
install:
  - pip install --upgrade poetry
  - poetry install
matrix:
  include:
  - name: "Lint and static analysis"
    python: 3.6
    script:
      - poetry run ./scripts/copyright_line_check.sh
      - poetry run black --check --config pyproject.toml .
      - poetry run flake8 --config setup.cfg . d
      - poetry run isort --check --settings-path setup.cfg -rc .
  - name: "Unit Tests"
    python: 3.6
    script:
      - poetry run python -m pytest .
